### ISSUE TITLE
syntax error, unexpected 'endwhile' (T_ENDWHILE), expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)

### ISSUE THREAD

**Issue by Eric-Miao** [dyedd/lanstar#1]
在启用lanstar之后，后台可以正常操作，但是无法回到预览界面，报错如下
syntax error, unexpected 'endwhile' (T_ENDWHILE), expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)

**Comment by dyedd** [comment]
你好，我这边没有找到这样的地方，能贴个图吗，后台我没有找到错误

**Comment by zhouzhou84** [comment]
![1](https://user-images.githubusercontent.com/33458022/92253347-f739fd80-ef01-11ea-8ed2-6a195f122fc1.png)

**Comment by Eric-Miao** [comment]
是这个没错，thx

**Comment by dyedd** [comment]
2有解决方法，关闭这个啦
