### ISSUE TITLE
启用主题后报错

### ISSUE THREAD

**Issue by ValentinLiu15** [dyedd/lanstar#12]
问题：RT，后台也报错了。
环境：PHP7.2
网站：https://blog.levimarvin.site
内容：syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)

**Comment by MeetinaXD** [comment]
同

**Comment by dyedd** [comment]
使用php7.4

**Comment by ZiXia1** [comment]
> 使用php7.4

能否支持一下7.2， 1G内存装7.4安装不了fileinfo
