### ISSUE TITLE
Emoji表情显示出错

### ISSUE THREAD

**Issue by liups233** [dyedd/lanstar#13]
- 图标能正常显示，但发送出来显示问号
![image](https://user-images.githubusercontent.com/45306747/108067244-7af43a80-709b-11eb-8f00-c5d2aa899ce4.png)

**Comment by zaochih** [comment]
试试更改数据库格式为unicode_utf8mb4

**Comment by liups233** [comment]
> 试试更改数据库格式为unicode_utf8mb4

厉害，可以了。我记得当时宝塔创建数据库时选的utf8mb4，但有的数据表是utf8，还要再phpMyAdmin下重新设置。
