### ISSUE TITLE
手机适配问题

### ISSUE THREAD

**Issue by ZiXia1** [dyedd/lanstar#15]
以手机分辨率访问，右栏个人信息会错位，移到页面下

**Comment by ZiXia1** [comment]
@dyedd

**Comment by dyedd** [comment]
来个图，看看

**Comment by ZiXia1** [comment]
> 来个图，看看

建议删去，或者改成joe主题手机页那样
https://ae01.alicdn.com/kf/Ue24f316153d140539c75a06eaee0abb7F.jpg

手机端点击导航栏得手动拉到顶部才能看见
https://ae01.alicdn.com/kf/Uffe0f57603db4e258822497006f88b91d.jpg
https://ae01.alicdn.com/kf/U8ffd4291d9e8487a95d51836531af84fl.jpg

建议添加灯箱，文章目录，代码高亮等东西，感觉缺的东西有点多

**Comment by dyedd** [comment]
> 灯箱，文章目录，代码高亮

灯箱，文章目录，代码高亮都存在

**Comment by define9** [comment]
@media (min-width: 768px)啥的自己加到main.css就行吧
