### ISSUE TITLE
确实有个error

### ISSUE THREAD

**Issue by zhouzhou84** [dyedd/lanstar#2]
截图如下
![1](https://user-images.githubusercontent.com/33458022/92253427-0faa1800-ef02-11ea-89e8-46f64bbb5b09.png)

**Comment by zhouzhou84** [comment]
修复好了告诉我一下，挺好看的主题
邮箱uu@uuiuu.uu.me

**Comment by zhouzhou84** [comment]
他们说的预览界面就是把文件夹上传到theme里后，更换主题，换成你的，然后再进网站就会出现这个截图，你可以把你的服务器的theme的lanstar主题删掉，换成github这个，然后再启用，应该也会出现这个问题。。。。

**Comment by dyedd** [comment]
> 他们说的预览界面就是把文件夹上传到theme里后，更换主题，换成你的，然后再进网站就会出现这个截图，你可以把你的服务器的theme的lanstar主题删掉，换成github这个，然后再启用，应该也会出现这个问题。。。。

我试过了，我本地没有这样的问题

**Comment by zhouzhou84** [comment]
额，那真的是怪了

**Comment by dyedd** [comment]
有没有安装什么插件，我从默认切换到这个，再去前台，就很正常的，如果可以的话，可以加qq群1147056149，再详细看看问题

**Comment by zhouzhou84** [comment]
没有安装任何插件，刚装的typecho，第一个用的你的主题

**Comment by dyedd** [comment]
我看了下index.php，没有什么语法错误..
那么得看看php.ini里面的short_open_tag标签有没有开启，

**Comment by TML233** [comment]
> 我看了下index.php，没有什么语法错误..
> 那么得看看php.ini里面的short_open_tag标签有没有开启，

谢谢，问题解决了，确实是short_open_tag没有设成On

**Comment by zhouzhou84** [comment]
> > 我看了下index.php，没有什么语法错误..
> > 那么得看看php.ini里面的short_open_tag标签有没有开启，
> 
> 谢谢，问题解决了，确实是short_open_tag没有设成On

在哪里设置的呀？

**Comment by dyedd** [comment]
> > > 我看了下index.php，没有什么语法错误..
> > > 那么得看看php.ini里面的short_open_tag标签有没有开启，
> > 
> > 
> > 谢谢，问题解决了，确实是short_open_tag没有设成On
> 
> 在哪里设置的呀？

php.ini typecho都是用尖括号当模板引擎的，可能有些人的php环境没有启用

**Comment by TML233** [comment]
> > > 我看了下index.php，没有什么语法错误..
> > > 那么得看看php.ini里面的short_open_tag标签有没有开启，
> > 
> > 
> > 谢谢，问题解决了，确实是short_open_tag没有设成On
> 
> 在哪里设置的呀？

根据环境的区别，php.ini的位置都不太一样，具体可以查一下，我的是Ubuntu, Apache2, PHP 7.4，在/etc/php/7.4/apache2/php.ini，搜索short_open_tag = Off 改成 On 就可以了
