### ISSUE TITLE
启用主题的时候遇到了报错

### ISSUE THREAD

**Issue by shanhaishi** [dyedd/lanstar#22]
报错内容
`Parse error: syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /www/wwwroot/blog_typecho/usr/themes/lanstar/libs/utils.php on line 482`
主题文件夹也改成了lanstar了，我不会php和前端所以有点无从下手，不知道哪的问题

**Comment by dyedd** [comment]
现在不在，可能会晚收 -自动回复

**Comment by shanhaishi** [comment]
> 现在不在，可能会晚收 -自动回复

不好意思，刚才在已经关闭的issues里找到解决方案了，是我的php版本太低了。现在问题已经解决了。
用github比较少，所以没事先去关闭的issues里找，不好意思了。
