### ISSUE TITLE
[bug？]侧边栏设置里的媒体信息配置无效

### ISSUE THREAD

**Issue by happytbs** [dyedd/lanstar#29]
![image](https://user-images.githubusercontent.com/74001578/160106972-ff966bdc-8e3f-435a-bdd4-06a29c3c98d3.png)
配置界面👆
————————————
在设置里配置前
![image](https://user-images.githubusercontent.com/74001578/160107108-3fdde5ad-cf75-4083-89b1-8846d50ff3c5.png)
配置后
![image](https://user-images.githubusercontent.com/74001578/160107159-ac4d5da4-37a6-4e62-9d2c-9adc03fe5259.png)

配置没有生效::>_<::

在文章底部也有一个无效的按钮
![image](https://user-images.githubusercontent.com/74001578/160107292-e7c6db09-1e6e-438a-8af9-4314af184c6d.png)
可能作者没来得及写

**Comment by dyedd** [comment]
http://lanstar.dyedd.cn/#/icon
关于图标添加请看这个文章，这个媒体功能我测试是没有问题的

**Comment by githubwkk** [comment]
![image](https://user-images.githubusercontent.com/80952394/193729810-d48d4bde-a7a5-47c0-922a-9a18dd322e0e.png)
还是不行，图标无法显示

**Comment by dyedd** [comment]
> ![image](https://user-images.githubusercontent.com/80952394/193729810-d48d4bde-a7a5-47c0-922a-9a18dd322e0e.png) 还是不行，图标无法显示

图片所示的图标没有内置，可能查看文档

**Comment by githubwkk** [comment]
> > ![image](https://user-images.githubusercontent.com/80952394/193729810-d48d4bde-a7a5-47c0-922a-9a18dd322e0e.png) 还是不行，图标无法显示
> 
> 图片所示的图标没有内置，可能查看文档

这个我看过了，现在的问题是是不是不能看到主题里面内置了那些图标？   如果要自定义，去阿里云图标库下载文件替换（还是添加？）icon.js文件（或者另外建一个图标js文件），再通过<script src=""></script>引入就行了？

**Comment by dyedd** [comment]
> > > ![image](https://user-images.githubusercontent.com/80952394/193729810-d48d4bde-a7a5-47c0-922a-9a18dd322e0e.png) 还是不行，图标无法显示
> > 
> > 
> > 图片所示的图标没有内置，可能查看文档
> 
> 这个我看过了，现在的问题是是不是不能看到主题里面内置了那些图标？ 如果要自定义，去阿里云图标库下载文件替换（还是添加？）icon.js文件（或者另外建一个图标js文件），再通过<script src=""></script>引入就行了？

不用替换，后台设置有个媒体扩展，把js链接放进去就行
