### ISSUE TITLE
小bug夜间模式下部分文字颜色错误

### ISSUE THREAD

**Issue by happytbs** [dyedd/lanstar#30]
![image](https://user-images.githubusercontent.com/74001578/160243879-60fc4876-6efd-4949-b363-319908a776f0.png)
在夜间模式下一些文字无法显示
——————————
![image](https://user-images.githubusercontent.com/74001578/160243904-c7ac7ee6-f604-4067-8a49-5a7283a3aae9.png)
也不知道作者在评论功能里加一个这个干什么……

**Comment by dyedd** [comment]
第二张是私密评论的意思
