### ISSUE TITLE
广告栏的buggg

### ISSUE THREAD

**Issue by happytbs** [dyedd/lanstar#31]
![image](https://user-images.githubusercontent.com/74001578/166098089-ad73cc9a-8696-4a9d-bb25-c5a9f9ad1288.png)
在我设置广告栏次数小于3的时候他会自动切换，切换之后就变成了空白
这个bug在3.1版本以前没有的。
自从3.1更新之后就有了

**Comment by dyedd** [comment]
现在不在，可能会晚收 -自动回复

**Comment by dyedd** [comment]
如我的博客，我就设置一个，没有切换空白，贴出你的配置选项就知道问题了

**Comment by happytbs** [comment]
我这边就有这个

**Comment by dyedd** [comment]
> 我这边就有这个

把选项值复制出来

**Comment by happytbs** [comment]
这个问题还没解决吗

**Comment by dyedd** [comment]
主要是我无法复现这个问题

> 这个问题还没解决吗
