### ISSUE TITLE
数学公式好像不支持？

### ISSUE THREAD

**Issue by Tlntin** [dyedd/lanstar#33]
比如在markdown编辑的$xxx$不起作用。
例如
`$O(m+n)$`
在文章中显示仍然为
`$O(m+n)$`

而不是显示为
$O(m+n)$

**Comment by dyedd** [comment]
markdown不支持数学公式的

**Comment by Tlntin** [comment]
已解决：
![image](https://user-images.githubusercontent.com/28218658/180677517-8e89c298-8408-4436-ba45-3090570cf0a8.png)
通过启动该插件即可实现Latex渲染。
https://github.com/gogobody/TypechoLaTeX
