### ISSUE TITLE
暗黑模式无法自动启用，手机端更多按钮（三横杠）点击无反应

### ISSUE THREAD

**Issue by XdxdGkld** [dyedd/lanstar#36]
![image](https://user-images.githubusercontent.com/79323102/207411990-e5b872e4-0d76-47b7-bfb7-324b46f90459.png)
如图所示的夜间模式和更多按钮都无法使用，无论手机电脑端， 并且暗黑模式自动切换也无反应，使用之前版本的主题暂无问题，比较迷惑
我的博客网站：blog.chenxiao.fun
一直都能复现，比较影响使用，望作者大大看看啥问题捏
![image](https://user-images.githubusercontent.com/79323102/207412176-305ed21e-01a9-4541-b81d-c698c614e09e.png)

**Comment by dyedd** [comment]
在目前的master主分支上已经修复了这个问题。你可以[去这里复制最新的内容](https://github.com/dyedd/lanstar/blob/master/component/index.footer.php)，覆盖这个文件内容。

**Comment by XdxdGkld** [comment]
> 在目前的master主要支持上已经修复了这个问题。你可以[去这里修复最新的内容](https://github.com/dyedd/lanstar/blob/master/component/index.footer.php)，覆盖这个文件的内容。

感谢回复，已经修改完成没问题了，不过很奇怪安装的是最新版的主题出现的问题
