### ISSUE TITLE
文章页面 分享按钮，复制链接按钮无效

### ISSUE THREAD

**Issue by qiaofugui** [dyedd/lanstar#38]
![image](https://user-images.githubusercontent.com/86886966/213344807-2737ecc4-a7fc-4446-be42-863d753a2291.png)

**Comment by qiaofugui** [comment]
可以使用一下 clipboard 库压缩后也才3kb，下面是简单修复了一下，作者可以抽离出来修复 

![image](https://user-images.githubusercontent.com/86886966/213348409-a280df9c-686d-4d3a-a97b-054a67977808.png)

**Comment by dyedd** [comment]
好的，我使用`Clipboard API`重新写了这个功能,低于3KB😜
