### ISSUE TITLE
无法设置外观

### ISSUE THREAD

**Issue by ghost** [dyedd/lanstar#39]
在http://example.com/admin/options-theme.php页面遇到### 500:

Typecho\I18n\GetText::translate(): Return value must be of type string, null returned

[在排查插件以后发现主题与jkOptionsFramework(一款选项框架>>(https://www.ijkxs.com/7153.html))冲突,希望解决一下

**Comment by dyedd** [comment]
这个插件是一个UI框架，还有哪些插件用到这个插件

**Comment by ghost** [comment]
> 这个插件是一个UI框架，还有哪些插件用到这个插件

	jkSiteHelper 是 Typecho 的一款站长工具箱>>https://www.ijkxs.com/7175.html

**Comment by dyedd** [comment]
已修复，请直接下载仓库最新的代码
