### ISSUE TITLE
Call to undefined function json_encode()

### ISSUE THREAD

**Issue by 1live** [dyedd/lanstar#4]
centos8 Lamp
使用官方主题、个别第三方主题没有问题。

之前出现和第一个第二个issues一样的问题，修改php.ini后便出现这样的提示：
Call to undefined function json_encode()

网上找了下，好多答案是Call to undefined function json_decode()指出要更新php-common，按照要求做没有结果；
关于Call to undefined function json_encode()的结果都指出和php-json文件有关，但是centos不能直接安装，，，网上的方式和我实际不符，给出的php-json链接都失效了。。。

; When floats & doubles are serialized, store serialize_precision significant
; digits after the floating point. The default value ensures that when floats
; are decoded with unserialize, the data will remain the same.
; The value is also used for json_encode when encoding double values.
; If -1 is used, then dtoa mode 0 is used which automatically select the best
; precision.
serialize_precision = -1
php.ini里边与json有关的只有这一个，链接到了etc/php.d里边也没有json相关文件。

我好奇的是，为什么现在没有一个合适的链接，难道大家都不需要这个文件了吗

**Comment by dyedd** [comment]
0.0 的确大家都没有这个问题...修改php.ini是不是改错了

**Comment by 1live** [comment]
> 0.0 的确大家都没有这个问题...修改php.ini是不是改错了

谢谢，我再看看如果是其它问题我再回来回复吧哈哈

**Comment by 1live** [comment]
我放弃了……
之前用的是php7.2，缺少php-json，在网上找了编译不进去……
后来觉得是不是7.2就不合适，重装了服务器，用了php7.4，然后修改了php.ini打开了short_open_tag
没想到这次连syntax error, unexpected 'endwhile' (T_ENDWHILE),的问题都解决不了了……

很好看的主题，下次装环境的时候再试试。

**Comment by 1live** [comment]
对了，php7.4好像是自带php-json的，所以如果能在这个环境下解决第一个问题，应该就没有我这个问题了。

**Comment by dyedd** [comment]
> 对了，php7.4好像是自带php-json的，所以如果能在这个环境下解决第一个问题，应该就没有我这个问题了。

我就是在php7.4下开发的...没这个问题

**Comment by 1live** [comment]
我就是用不了，，，，，蓝瘦。。。

**Comment by dyedd** [comment]
你加下群，详细说说
