### ISSUE TITLE
文章的标题界面没有图标

### ISSUE THREAD

**Issue by Hope-you** [dyedd/lanstar#41]
![image](https://user-images.githubusercontent.com/34697553/228473320-5e4027fd-c08b-49ad-9207-8071e71c0553.png)

**Comment by dyedd** [comment]
后台》管理》分类》编辑分类中，在分类描述里填入你想要自定义的图片地址

**Comment by Hope-you** [comment]
> 后台》管理》分类》编辑分类中，在分类描述里填入你想要自定义的图片地址

我就说图片地址怎么是我的描述，懂了。
