### ISSUE TITLE
主题的大小不协调呢

### ISSUE THREAD

**Issue by pipuwong** [dyedd/lanstar#44]
主题的大小不协调呢

**Comment by dyedd** [comment]
有没有更详细的信息呢？

**Comment by pipuwong** [comment]
你好，我已收到你的e-mail，谢谢。

**Comment by yinmoyu** [comment]
> 有没有更详细的信息呢？

- 字体小行间距小，有点过于密集，影响阅读体验。

- 首页的文章只能点击查看文章才能打开，点标题和缩略都不行。

- 目录按钮有bug，在首页也会显示，在文章页打开目录后会盖住目录按钮，需要点击右上角的x才能关闭，可以考虑做成悬浮的。

主题很好，要是能稍作完善会更受欢迎。
