### ISSUE TITLE
hello，我使用后有多处图片不显示

### ISSUE THREAD

**Issue by lettimepassby** [dyedd/lanstar#45]
![QQ截图20230927172636](https://github.com/dyedd/lanstar/assets/52483607/1a0962b9-5ff7-4a73-8492-2f7e818b88a6)
![QQ截图20230927172652](https://github.com/dyedd/lanstar/assets/52483607/80f8d110-b40a-4728-a204-0fefb21fea2c)
希望得到帮助，感谢

**Comment by dyedd** [comment]
你好，请问有地址吗？

**Comment by lettimepassby** [comment]
> 你好，请问有地址吗？

您好：blog.timepas.cn

**Comment by dyedd** [comment]
1. 日常处，在管理-分类-分类描述里添加图片链接
2. 表情请检查`usr/themes/lanstar/assets/owo/`是否有目录

**Comment by lettimepassby** [comment]
> 1. 日常处，在管理-分类-分类描述里添加图片链接
> 2. 表情请检查`usr/themes/lanstar/assets/owo/`是否有目录

感谢！其中问题一已被解决，问题二检查过了有目录，目录内的文件内容正常

**Comment by dyedd** [comment]
那看看owo目录的权限是多少，php版本要7，8左右，是不是开启了防盗链等限制访问的行为

**Comment by lettimepassby** [comment]
权限777 所有者www php7.4 未开启防盗链等限制访问行为

**Comment by dyedd** [comment]
我看你的图片都是外链，你先试试在你typecho上传一个图片，看看能不能显示

**Comment by dyedd** [comment]
我知道是什么原因，你的模板文件名得是小写的`lanstar`，现在你的目录第一个l大写了，所以表情无法显示！

**Comment by lettimepassby** [comment]
> 我知道是什么原因，你的模板文件名得是小写的`lanstar`，现在你的目录第一个l大写了，所以表情无法显示！

！可以正常显示了！感谢!
