### ISSUE TITLE
[问题]网站后台地址隐藏

### ISSUE THREAD

**Issue by Rockney99** [dyedd/lanstar#48]
安装主题后侧边栏显示后台把登录地址曝光了 该怎么隐藏  建议下次更新能手动设置或直接不显示登录地址
![image](https://github.com/dyedd/lanstar/assets/42824224/f20b1176-3f91-48d8-aed0-c14f8eb5a225)

**Comment by dyedd** [comment]
1. 首先需要说明的一点是，**后台的显示**是因为**用户登录**了，如果**你退出**是不会显示后台按钮的！
2. 如果你要删除，可以参照下面的流程：（实际上没有必要）
在`[layout](https://github.com/dyedd/lanstar/tree/master/layout)
/left.php`,删除39-48行代码：
```php
<?php if ($this->user->hasLogin()): ?>
        <div class="nav-item">
            <a class="nav-link" href="<?php $this->options->adminUrl(); ?>" title="进入后台">
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-shezhi"></use>
                </svg>
                <span class="nav-item-text">后台</span>
            </a>
        </div>
    <?php endif; ?>
```
