### ISSUE TITLE
使用主题lanstar-2.1.2，显示你选择的风格不存在

### ISSUE THREAD

**Issue by duktig666** [dyedd/lanstar#5]

**Comment by dyedd** [comment]
应该没有把文件夹重命名为`lanstar`

**Comment by duktig666** [comment]
重命名为`lanstar`后，换了新的报错，首页显示：   `syntax error, unexpected 'else' (T_ELSE)`

**Comment by duktig666** [comment]
可惜我是学Java的对PHP没有怎么涉猎，要不可以研究研究

**Comment by dyedd** [comment]
试试  [2](https://github.com/dyedd/lanstar/issues/2)？

**Comment by duktig666** [comment]
v2.1.1稳定吗？想试试这个黑夜白昼切换

**Comment by dyedd** [comment]
稳定

> v2.1.1稳定吗？想试试这个黑夜白昼切换

**Comment by duktig666** [comment]
好的，我试试v2.1.1

**Comment by duktig666** [comment]
> 稳定
> 
> > v2.1.1稳定吗？想试试这个黑夜白昼切换

刚才试了试v2.1.1还是同样的错误。  `syntax error, unexpected 'else' (T_ELSE)`

**Comment by dyedd** [comment]
我认为是你这个服务器不支持php的短代码标记

**Comment by dyedd** [comment]
所以可以试试我之前发的这个

> 试试 [2](https://github.com/dyedd/lanstar/issues/2)？

**Comment by duktig666** [comment]
> 我认为是你这个服务器不支持php的短代码标记

用v2.0吗

**Comment by duktig666** [comment]
> 我认为是你这个服务器不支持php的短代码标记

对PHP确实没有研究，基本都是Java环境，不过我是用docker环境部署的项目

**Comment by dyedd** [comment]
> > 我认为是你这个服务器不支持php的短代码标记
> 
> 用v2.0吗

不不，你只要开启短代码就行，这个所有版本都要用到这个

**Comment by duktig666** [comment]
短代码是啥，学Java的一脸懵逼。

我是用用docker部署的typecho

**Comment by dyedd** [comment]
php.ini，搜索short_open_tag = Off 改成 On 就可以了

**Comment by duktig666** [comment]
我是基于这样的方式部署的typecho：[https://blog.csdn.net/qq_41861526/article/details/103459472](https://blog.csdn.net/qq_41861526/article/details/103459472)

**Comment by dyedd** [comment]
> 我是基于这样的方式部署的typecho：https://blog.csdn.net/qq_41861526/article/details/103459472

https://www.nuomiphp.com/article/74.html

**Comment by duktig666** [comment]
#### 解决
解决了，无意间被学Java的我凭感觉被我试出来了。他这个typecho镜像的`php.ini`位置在`/etc/php7`下，修改`short_open_tag = Off`后重启docker镜像就解决问题了。

#### typecho  docker镜像地址
这是这个docker镜像地址：[https://hub.docker.com/search?q=80x86%2Ftypecho&type=image](https://hub.docker.com/search?q=80x86%2Ftypecho&type=image)

#### 建议
感觉lanstar主题可以兼容一下这个问题，或者可以给这个镜像官方反应一下这个问题。期待下个版本可以兼容解决一下。哈哈。
