### ISSUE TITLE
新年更新后，一些功能缺失或出错

### ISSUE THREAD

**Issue by liups233** [dyedd/lanstar#6]
- 「自定义导航小图片」不可用。
- 「jsdelivr加速」启用后站点排版出错。
- 站点logo旁边的站点名称没了QAQ

**Comment by dyedd** [comment]
导航图标，那个明天有时候会写文档，用的是iconfont
目前版本因为打包标签为2.0不是2.0.0，所有出错了
因为现在的logo替代了站点名称，可能处于考虑出个没有logo显示文字的功能

**Comment by liups233** [comment]
感谢回复
